### ISSUE TITLE
Required Packages

### ISSUE THREAD

**Issue by richpeck** [phpenv/phpenv-installer#1]
This is more of a comment than an issue; to get PHP versions installed on Ubuntu, the following packages are required (props to [this article](https://techhub.erimy.net/archives/7-e-33-a-909935949-dd-6-ec-7) for most of them):

`sudo apt install build-essential pkg-config libxml2-dev libkrb5-dev libssl-dev libsqlite3-dev libbz2-dev libpng-dev libjpeg-dev libonig-dev libreadline-dev libtidy-dev libxslt-dev libzip-dev libcurl4 libcurl4-openssl-dev`

`PHPEnv` installs properly without these, but installing actual PHP versions will fail unless the above are installed.

**Comment by debo** [comment]
Hi @richpeck thanks for your comment, really appreciated. You are right in saying this is not an issue, but that's only true for phpenv-installer whose goal is only to help installing phpenv and some of it's immediate dependencies. When it comes to build PHP version instead it's a different story and what you pointed out is true, and we discussed it in various forms and shape as part of [this issue](https://github.com/phpenv/phpenv/issues/90) I'm also sure those dependencies are documented somewhere as part of either phpenv or phpbuild but now I can't seem to be able to find them.

I hope that helps/clarify.

**Comment by richpeck** [comment]
Thanks, I posted as a reference as I couldn't find anything apart from the aforementioned article.

**Comment by debo** [comment]
No problem at all, you did well, sometimes informations are out there but hard to find so you have all my sympathy and support. Thanks for raising this, we will try to make the requirements clearer.
