### ISSUE TITLE
No package 'oniguruma' found

### ISSUE THREAD

**Issue by mouday** [phpenv/phpenv-installer#6]
$ phpenv install 8.1.2
[Info]: Loaded extension plugin
[Info]: Loaded apc Plugin.
[Info]: Loaded composer Plugin.
[Info]: Loaded github Plugin.
[Info]: Loaded uprofiler Plugin.
[Info]: Loaded xdebug Plugin.
[Info]: Loaded xhprof Plugin.
[Info]: Loaded zendopcache Plugin.
[Info]: php.ini-production gets used as php.ini
[Info]: Building 8.1.2 into ~/.phpenv/versions/8.1.2
[Skipping]: Already downloaded and extracted https://www.php.net/distributions/php-8.1.2.tar.bz2
[Preparing]: /var/tmp/php-build/source/8.1.2

-----------------
|  BUILD ERROR  |
-----------------

Here are the last 10 lines from the log:

-----------------------------------------
configure: error: Package requirements (oniguruma) were not met:

No package 'oniguruma' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables ONIG_CFLAGS
and ONIG_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
-----------------------------------------

The full Log is available at '/tmp/php-build.8.1.2.20220224220325.log'.
[Warn]: Aborting build.

**Comment by debo** [comment]
Hi @mouday did you try installing the missing package mentioned in the error?

**Comment by madalinignisca** [comment]
php-build is not responsible on handling your distribution package manager to install development needed packages.

PHP is a thin wrapper on top of a lot of C/C++ applications/libraries. Those must exist in the system that does the build, and considering that from MacOS to Debian to Arch Linux all are packaged different, no project can sustain all possible methods of getting them installed silent and magically for the user.

I recommend if you want to use phpenv with php-build, that you already know how to handle your package manager to search and install missing pieces.

Alternative, it would be awesome if people would contribute to php-build and we would create pre-built php distributions like nodenv uses for example for nodejs. Makes life easy to everybody. Although, this method would be questioned by many for guarantee of safety.

**Comment by nickl-** [comment]
Closed: out of scope
